openapi: 3.0.2 
info:
  title: Course Class Service API Specification
  description: OpenAPI for Course Class API
  version: 1
servers:
  - url: http://localhost:8000
    description: Course Class Service API Server
externalDocs:
  - url: https://github.com/catherinevania/microservice-obe
    description: Github Repository
paths:
  /course-classes:
    get:
      summary: Get all courses
      description: View all courses from database
      responses:
        '200':
          description: Succesfully get all courses
          content: 
            application/json: 
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    study_program:
                      type: integer
                    code:
                      type: string
                    name: 
                      type: string
                    course_credit:
                      type: integer
                    lab_credit:
                      type: integer
                    type:
                      type: string
                    short_description:
                      type: string
                    minimal_requirement:
                      type: string
                    study_material_summary:
                      type: string
                    learning_media:
                      type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:

  /course-classes/{id}:
    get:
      summary: Get a class by ID
      description: View a class with certain ID
      parameters:
        - name: id
          in: path
          description: ID of the class to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succesfully get class by ID
          content: 
            application/json:
              schema: 
                type: object
                properties:
                    name:
                      type: string
                    course_id:
                      type: integer
                    syllabus_id:
                      type: integer
                    thumbnail_img:
                      type: string
                      contentMediaType: image/png
                      contentEncoding: base64     
        '404':
          description: Course not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 

    patch:

    delete:
